### ISSUE TITLE
Garuda

### ISSUE THREAD

**Issue by Sha-a-Gi** [KCkingcollin/ussedp#7]
Seems to spit out this for me, maybe an issue due to the install being on another drive?

System.IO.FileNotFoundException: Could not find file '/home/rhinlord/ussedp-BestOfBothWorlds/instructions.json'.
File name: '/home/rhinlord/ussedp-BestOfBothWorlds/instructions.json'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytesAsync(String path, CancellationToken cancellationToken)
   at Ussedp.Extractor.LoadFile(String name) in /home/rhinlord/ussedp/Patcher/Extractor.cs:line 74
   at Patcher.ViewModels.MainWindowViewModel.Start() in /home/rhinlord/ussedp/Patcher/ViewModels/MainWindowViewModel.cs:line 85
Error! Could not find file '/home/rhinlord/ussedp-BestOfBothWorlds/instructions.json'.
Running instructions
No header magic found
Checking for magic header in /home/rhinlord/ussedp-BestOfBothWorlds/Patcher
Found at /run/media/rhinlord/Extend/ExtendSteamLibrary/steamapps/common/Skyrim Special Edition
Looking for Skyrim Special Edition

*edit: issue with linux_main

**Comment by KCkingcollin** [comment]
Sorry for getting back to you so late been really busy at work, but it looks like the patch files didn't get installed for some reason, I'll take a look into fixing this asap

**Comment by KCkingcollin** [comment]
Is the file `ussedp-patches.7z` in the `~/ussedp` location?
If so what do you see when you open it...

**Comment by KCkingcollin** [comment]
im afraid i cant really help if i don't have any information to work off of ill try to test garuda on its own later but as far as i know the script has worked with both base arch and manjaro so by extension it should work on garuda. for now im closing this until i can test it myself, but that might be a while as i currently have bigger fish to fry...
