### ISSUE TITLE
JsonException upon running patcher

### ISSUE THREAD

**Issue by hol430** [KCkingcollin/ussedp#9]
Hi, firstly thanks for all the work you've put into this project.

When I run this on arch linux, I get a JsonException after clicking the "start patching" button in the GUI. This happens for both patching methods. The log displayed in the GUI is:

```
System.Text.Json.JsonException: The JSON value could not be converted to DTOs.BuildRecord. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at Patcher.ViewModels.MainWindowViewModel.Start()
Error! The JSON value could not be converted to DTOs.BuildRecord. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
Running instructions
No header magic found
Checking for magic header in /home/<username>/ussedp-BestOfBoth/Patcher
Found at /path/to/steamapps/common/Skyrim Special Edition
Looking for Skyrim Special Edition
```

Let me know if there is any extra info/logs I can provide. Happy to run any tests which you think may be helpful.

**Comment by hol430** [comment]
Looks like the problem is that upstream have changed the expected type of the object stored in instructions.json. @KCkingcollin do you have any plans to update the scripts/patch files to account for the upstream changes?

For what it's worth, I'm able to work around the problem by changing the auto-compile script to clone this repo instead, however I still run into a hash mismatch error when patching one of the files:

```
System.Exception: Can't patch file SkyrimSE.exe, it doesn't match the expected format
   at Patcher.ViewModels.MainWindowViewModel.PatchFile(Instruction file, AbsolutePath gamePath) in /home/drew/ussedp/Patcher/ViewModels/MainWindowViewModel.cs:line 134
   at Patcher.ViewModels.MainWindowViewModel.Start() in /home/drew/ussedp/Patcher/ViewModels/MainWindowViewModel.cs:line 108
Error! Can't patch file SkyrimSE.exe, it doesn't match the expected format
```

**Comment by KCkingcollin** [comment]
i am terribly sorry for seeing this so late for some reason git does not notify me of anything...
ill get onto this right away

**Comment by KCkingcollin** [comment]
From the looks of things my script is just out of date, and there are ether new patch files or the downloader was reimplemented into the original patcher, so far it looks like the latter, so I'll see if I can make the proper adjustments, and maybe take a look at his license agreement to see if I'm able to just compile a version of the patcher and release that

**Comment by KCkingcollin** [comment]
Update: he has an open source license, so I'll be making peoples lives a bit easier and just compile a version of his patcher, but just in case I'll also update the scripts

**Comment by KCkingcollin** [comment]
update: I've tried a few things but it seems the patch files are not being updated on nexus, and as far as I know they are not hosted anywhere else, I dont think we have any other choice but to wait

**Comment by hol430** [comment]
Thanks for the update - that makes sense. I wonder if it's possible to extract the patch files from the executable on the nexus. I may look into that if I can find some time....

> git does not notify me of anything

Probably just need to watch the repository

![image](https://user-images.githubusercontent.com/36427516/158966689-d971777b-4097-4f46-88ef-5ff8ee86b0df.png)

**Comment by KCkingcollin** [comment]
Damn lol I just assumed my own repo was auto watched how stupid of me, but I've kinda left this project stagnant for now as it seems 90% of Skyrim SE mod were moved over to AE and a bunch more SE mods seem to be working now, plus proton seems to have been working for AE for a while so I guess there isn't really a need for this tool in my eyes

**Comment by hol430** [comment]
Yes, that was my conclusion too when I revisited this a few weeks ago. Regardless, thanks for all the effort you've put into this!

**Comment by KCkingcollin** [comment]
No problem, sorry I've been so absent from git

**Comment by Kurumi78** [comment]
Is there going to be any more work done on this? there are still a lot of mods that are not updated for AE that I would enjoy using.

**Comment by KCkingcollin** [comment]
Sorry doubt it, true some mods arnt working, but most are if you take the right steps, plus even if i did continue this project it wouldn't go far due to the necessary files not being available, for the most part the original owner of ussedp hasn't been keeping up with giving us up to date patch files so i cant really fix it anyway

your best option is to try getting it working in wine or proton, or just try and get as many mods working as you can sorry, and good luck

btw i have 200+ mods on my install, and all work fine with the exception of i think a few, are you sure you've taken all the right steps to getting your mods working?
